version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn --version

  pre_build:
    commands:
      - echo Pre-build started

  build:
    commands:
      - echo Build started
      - mvn clean package -B
      - echo Listing target folder:
      - ls -l target

artifacts:
  files:
    - '*.war'
  base-directory: target
  discard-paths: yes
